docs(README): add information about provenance file
sigstore/helm-sigstore pull request #18
Opened 2021-12-09 14:24 UTC by developer-guy

#### Summary

#### Ticket Link

Fixes

#### Release Note

```release-note

```

2021-12-10 17:42 UTC, sabre1041 requested changes
Minor change requested

2021-12-10 17:42 UTC, sabre1041 commented on README.md
> +> To generate a provenance file, please reach out the official documentation of [Helm Provenance and Integrity](https://helm.sh/docs/topics/provenance/).
```suggestion
> To generate a provenance file, please consult the official documentation of [Helm Provenance and Integrity](https://helm.sh/docs/topics/provenance/).
```

2021-12-10 18:48 UTC, developer-guy commented on README.md
> +> To generate a provenance file, please reach out the official documentation of [Helm Provenance and Integrity](https://helm.sh/docs/topics/provenance/).
sorry about my poor English 🤦🏻‍♂️ fixed.

2021-12-13 01:20 UTC, sabre1041 approved these changes
LGTM

2021-12-13 01:20 UTC, merged