add goreleaser and update release job
sigstore/helm-sigstore pull request #27
Opened 2021-12-28 15:56 UTC by cpanato

#### Summary
- add goreleaser and update release job

#### Ticket Link

Fixes: https://github.com/sigstore/helm-sigstore/issues/26

#### Release Note

```release-note
add goreleaser and update release job
```

2021-12-29 22:01 UTC, sabre1041 requested changes
This is great work. One small addition is required.

I tried testing on my own fork and ran into issues uploading the artifacts to the release

https://github.com/sabre1041/helm-sigstore/actions/runs/1635015585

Note: I had to make some additional changes due to the forked repository, but take a look to see if anything jumps out

2021-12-30 09:02 UTC, cpanato commented on .github/workflows/release.yml
> +        run: make release
thanks for the review, missed that

2021-12-30 14:45 UTC, cpanato commented on .github/workflows/release.yml
> +        run: make release
found other issues in goreleaser that is fixed here https://github.com/goreleaser/goreleaser/pull/2798

2021-12-30 18:11 UTC, sabre1041 commented on .github/workflows/release.yml
> +        run: make release
Great fix upstream. Do we want to move forward without SBOM generation until its fixed upstream and then add it in once `v1.3.0`?

2022-01-03 13:09 UTC, cpanato commented
@sabre1041 done
you can check the rehearsal here: https://github.com/cpanato/helm-sigstore/runs/4691160707?check_suite_focus=true
and the release here: https://github.com/cpanato/helm-sigstore/releases/tag/v99.99.99

2022-01-03 15:28 UTC, sabre1041 approved these changes
LGTM

2022-01-03 15:32 UTC, merged

2022-01-03 15:32 UTC, sabre1041 commented
Thanks @cpanato for you efforts around this task!